version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies with yarn
          command: cd done && yarn
      - run:
          name: Run unit tests
          command: cd done && yarn test:unit

workflows:
  unit-tests:
    jobs:
      - build